// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GameController from "./game_controller"
application.register("game", GameController)

import GraduatedRangeController from "./graduated_range_controller"
application.register("graduated-range", GraduatedRangeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchbarController from "./searchbar_controller"
application.register("searchbar", SearchbarController)

import StarsController from "./stars_controller"
application.register("stars", StarsController)

import TapbarController from "./tapbar_controller"
application.register("tapbar", TapbarController)

import WeatherController from "./weather_controller"
application.register("weather", WeatherController)
