meta_product_name: "Product Name"
meta_title: "Scubapp - Product tagline"
meta_description: "Discover Scubapp, the ultimate dashboard for scuba divers! Explore the seabed with ease, thanks to our innovative application. Track your dives, save your favorite sites, share your experiences with a passionate community. Dive into the world of Scubapp and explore the oceans like never before!"
meta_image: "app/assets/images/banner_scubapp.avif" # should exist in `app/assets/images/`
