meta_name: "Application name"
meta_title: "Scubapp - Le dashboard pour plongeurs sous-marins"
meta_description: "Découvrez Scubapp, le dashboard ultime pour les plongeurs sous-marins ! Explorez les fonds marins en toute simplicité grâce à notre application innovante. Suivez vos plongées, enregistrez vos sites préférés, partagez vos expériences avec une communauté passionnée. Plongez dans l'univers de Scubapp et explorez les océans comme jamais auparavant !"
meta_image: "banner_scubapp.png"
